winget upgrade --all 
winget install Brave.Brave 
winget install CrystalDewWorld.CrystalDiskInfo 
winget install Git.Git 
winget install Microsoft.Edge   
winget install Microsoft.EdgeWebView2Runtime  
winget install Microsoft.AppInstaller  
winget install Microsoft.UI.Xaml.2.7  
winget install Microsoft.UI.Xaml.2.8  
winget install Microsoft.VCLibs.Desktop.14  
winget install Microsoft.WindowsTerminal.Preview  
winget install Valve.Steam  
winget install VideoLAN.VLC  
winget install RARLab.WinRAR  
winget install Microsoft.VCRedist.2015+.x64  
winget install Microsoft.PowerShell.Preview  
winget install Microsoft.VisualStudioCode  
winget install Nvidia.GeForceExperience  
winget install Amazon.AWSCLI  
winget install Microsoft.VCRedist.2015+.x64  
